
// The [throw] slot in Hyperlambda is used to raise an exception with a specified message. In this example, the exception message is "foo". When executed, this slot will interrupt the normal flow of the program and propagate the exception, which can be caught and handled by a [.catch] block if present.
throw:foo
