
// This Hyperlambda code attempts to perform an HTTP GET request to "https://invalid-url.com" within a [try] block, with the response being automatically converted to a lambda object if possible due to the [convert] argument set to true. If the URL is invalid or the request fails, an exception will be raised, which can be caught by a subsequent [.catch] block.
try
   http.get:"https://invalid-url.com"
      convert:true
