
// This Hyperlambda code attempts to load a file from a specified path using [io.file.load] and assigns its content to [.file-content]. If the file is not found, it catches the exception and logs an error message using [log.error]. The [try] and [.catch] slots are used for exception handling.
try
   try
      io.file.load:x:@.file-path
      set-value:x:@.file-content
         .:x:@io.file.load
   .catch
      log.error:File not found
