/*
 * Catches an error during a try block and logs it for further analysis.
 */
try
   throw:Something bad happened
.catch
   log.error:x:@.arguments/*/message
